package science.transductive.nudge.core;

import java.util.*;

public final class Models {
    private Models() {}
    public enum Attention { NORMAL, HEADS_UP, URGENT }
    public enum Capture { NONE, CHOICE, AUDIO }
    public enum ReceiptStatus { APPLIED, NOT_APPLIED, UNKNOWN_OUTCOME }
    public enum Delivery { IN_APP, NOTIFICATION, HEADS_UP, FULL_SCREEN }
    public enum Timing { IMMEDIATE, INEXACT_ALARM, EXACT_ALARM }

    public static final class Choice {
        private final String id,label;public Choice(String id,String label){this.id=id;this.label=label;}public String id(){return id;}public String label(){return label;}
        @Override public boolean equals(Object o){if(this==o)return true;if(!(o instanceof Choice))return false;Choice x=(Choice)o;return Objects.equals(id,x.id)&&Objects.equals(label,x.label);}@Override public int hashCode(){return Objects.hash(id,label);}
    }
    public static final class InteractionSpec {
        private final String protocol,interactionId,title,readyPrompt,prompt;private final long issuedAtMs,triggerAtMs,expiresAtMs,countdownMs;private final boolean readyGate,requiresExactTiming,requestFullScreen;private final Attention attention;private final Capture capture;private final List<Choice> choices;
        public InteractionSpec(String protocol,String interactionId,long issuedAtMs,long triggerAtMs,long expiresAtMs,String title,String readyPrompt,boolean readyGate,String prompt,Attention attention,Capture capture,List<Choice> choices,long countdownMs,boolean requiresExactTiming,boolean requestFullScreen){this.protocol=protocol;this.interactionId=interactionId;this.issuedAtMs=issuedAtMs;this.triggerAtMs=triggerAtMs;this.expiresAtMs=expiresAtMs;this.title=title;this.readyPrompt=readyPrompt;this.readyGate=readyGate;this.prompt=prompt;this.attention=attention;this.capture=capture;this.choices=Collections.unmodifiableList(new ArrayList<Choice>(choices==null?Collections.<Choice>emptyList():choices));this.countdownMs=countdownMs;this.requiresExactTiming=requiresExactTiming;this.requestFullScreen=requestFullScreen;}
        public String protocol(){return protocol;}public String interactionId(){return interactionId;}public long issuedAtMs(){return issuedAtMs;}public long triggerAtMs(){return triggerAtMs;}public long expiresAtMs(){return expiresAtMs;}public String title(){return title;}public String readyPrompt(){return readyPrompt;}public boolean readyGate(){return readyGate;}public String prompt(){return prompt;}public Attention attention(){return attention;}public Capture capture(){return capture;}public List<Choice> choices(){return choices;}public long countdownMs(){return countdownMs;}public boolean requiresExactTiming(){return requiresExactTiming;}public boolean requestFullScreen(){return requestFullScreen;}
        @Override public boolean equals(Object o){if(this==o)return true;if(!(o instanceof InteractionSpec))return false;InteractionSpec x=(InteractionSpec)o;return issuedAtMs==x.issuedAtMs&&triggerAtMs==x.triggerAtMs&&expiresAtMs==x.expiresAtMs&&readyGate==x.readyGate&&countdownMs==x.countdownMs&&requiresExactTiming==x.requiresExactTiming&&requestFullScreen==x.requestFullScreen&&Objects.equals(protocol,x.protocol)&&Objects.equals(interactionId,x.interactionId)&&Objects.equals(title,x.title)&&Objects.equals(readyPrompt,x.readyPrompt)&&Objects.equals(prompt,x.prompt)&&attention==x.attention&&capture==x.capture&&Objects.equals(choices,x.choices);}@Override public int hashCode(){return Objects.hash(protocol,interactionId,issuedAtMs,triggerAtMs,expiresAtMs,title,readyPrompt,readyGate,prompt,attention,capture,choices,countdownMs,requiresExactTiming,requestFullScreen);}
    }
    public static final class CapabilitySnapshot {private final boolean notifications,fullScreenIntent,exactAlarm,notificationPolicy,microphone,accessibility,userVisible;public CapabilitySnapshot(boolean notifications,boolean fullScreenIntent,boolean exactAlarm,boolean notificationPolicy,boolean microphone,boolean accessibility,boolean userVisible){this.notifications=notifications;this.fullScreenIntent=fullScreenIntent;this.exactAlarm=exactAlarm;this.notificationPolicy=notificationPolicy;this.microphone=microphone;this.accessibility=accessibility;this.userVisible=userVisible;}public boolean notifications(){return notifications;}public boolean fullScreenIntent(){return fullScreenIntent;}public boolean exactAlarm(){return exactAlarm;}public boolean notificationPolicy(){return notificationPolicy;}public boolean microphone(){return microphone;}public boolean accessibility(){return accessibility;}public boolean userVisible(){return userVisible;}}
    public static final class Plan {private final Delivery delivery;private final Timing timing;private final boolean canStartAudio;private final List<String> downgrades;public Plan(Delivery delivery,Timing timing,boolean canStartAudio,List<String> downgrades){this.delivery=delivery;this.timing=timing;this.canStartAudio=canStartAudio;this.downgrades=Collections.unmodifiableList(new ArrayList<String>(downgrades));}public Delivery delivery(){return delivery;}public Timing timing(){return timing;}public boolean canStartAudio(){return canStartAudio;}public List<String> downgrades(){return downgrades;}}
    public static final class ResponseEvent {private final String protocol,eventId,interactionId,choiceId,audioRef;private final long atMs;public ResponseEvent(String protocol,String eventId,String interactionId,long atMs,String choiceId,String audioRef){this.protocol=protocol;this.eventId=eventId;this.interactionId=interactionId;this.atMs=atMs;this.choiceId=choiceId;this.audioRef=audioRef;}public String protocol(){return protocol;}public String eventId(){return eventId;}public String interactionId(){return interactionId;}public long atMs(){return atMs;}public String choiceId(){return choiceId;}public String audioRef(){return audioRef;}}
    public static final class Receipt {private final String protocol,interactionId,evidence;private final ReceiptStatus status;private final long atMs;private final List<String> downgrades;public Receipt(String protocol,String interactionId,ReceiptStatus status,long atMs,String evidence,List<String> downgrades){this.protocol=protocol;this.interactionId=interactionId;this.status=status;this.atMs=atMs;this.evidence=evidence;this.downgrades=Collections.unmodifiableList(new ArrayList<String>(downgrades));}public String protocol(){return protocol;}public String interactionId(){return interactionId;}public ReceiptStatus status(){return status;}public long atMs(){return atMs;}public String evidence(){return evidence;}public List<String> downgrades(){return downgrades;}}
}
