package science.transductive.nudge.core;

import java.util.*;
import java.util.regex.Pattern;
import static science.transductive.nudge.core.Models.*;

public final class Protocol {
    public static final String VERSION="NUDGE_PROTOCOL/1";private static final Pattern ID=Pattern.compile("[A-Za-z0-9._:-]{1,160}");private Protocol(){}
    @SuppressWarnings("unchecked") public static InteractionSpec parseInteraction(String json){
        if(json==null||json.length()>64000)throw new IllegalArgumentException("interaction too large");Object root=MiniJson.parse(json);if(!(root instanceof Map))throw new IllegalArgumentException("root must be object");Map<String,Object>m=(Map<String,Object>)root;String protocol=reqString(m,"protocol");if(!VERSION.equals(protocol))throw new IllegalArgumentException("unsupported protocol: "+protocol);String id=reqString(m,"interactionId");long issued=num(m,"issuedAtMs",0),trigger=num(m,"triggerAtMs",issued),expires=num(m,"expiresAtMs",0);String title=str(m,"title",""),readyPrompt=str(m,"readyPrompt","READY?"),prompt=reqString(m,"prompt");boolean readyGate=bool(m,"readyGate",false);Attention attention=Attention.valueOf(str(m,"attention","NORMAL"));Capture capture=Capture.valueOf(str(m,"capture","NONE"));long countdown=num(m,"countdownMs",0);boolean exact=bool(m,"requiresExactTiming",false),full=bool(m,"requestFullScreen",false);List<Choice>choices=new ArrayList<Choice>();Object c=m.get("choices");if(c instanceof List)for(Object x:(List<?>)c){if(!(x instanceof Map))throw new IllegalArgumentException("choice must be object");Map<String,Object>cm=(Map<String,Object>)x;choices.add(new Choice(reqString(cm,"id"),reqString(cm,"label")));}InteractionSpec spec=new InteractionSpec(protocol,id,issued,trigger,expires,title,readyPrompt,readyGate,prompt,attention,capture,choices,countdown,exact,full);validateShape(spec);return spec;
    }
    public static void validateForNow(InteractionSpec s,long nowMs,Set<String>seen){validateShape(s);if(s.issuedAtMs()>nowMs+300000L)throw new IllegalArgumentException("issued in future");if(s.triggerAtMs()<s.issuedAtMs())throw new IllegalArgumentException("trigger before issue");if(s.triggerAtMs()>s.expiresAtMs())throw new IllegalArgumentException("trigger after expiry");if(s.expiresAtMs()<=nowMs)throw new IllegalArgumentException("expired");if(s.expiresAtMs()-s.issuedAtMs()>604800000L)throw new IllegalArgumentException("expiry window too large");if(seen.contains(s.interactionId()))throw new IllegalArgumentException("replay");}
    public static Plan plan(InteractionSpec s,CapabilitySnapshot c){List<String>d=new ArrayList<String>();Delivery delivery;if(!c.notifications()){delivery=Delivery.IN_APP;d.add("notifications_unavailable");}else if(s.attention()==Attention.URGENT&&s.requestFullScreen()&&c.fullScreenIntent())delivery=Delivery.FULL_SCREEN;else if(s.attention()==Attention.URGENT||s.attention()==Attention.HEADS_UP){delivery=Delivery.HEADS_UP;if(s.requestFullScreen()&&!c.fullScreenIntent())d.add("full_screen_unavailable");}else delivery=Delivery.NOTIFICATION;Timing timing=Timing.IMMEDIATE;if(s.requiresExactTiming()){if(c.exactAlarm())timing=Timing.EXACT_ALARM;else{timing=Timing.INEXACT_ALARM;d.add("exact_alarm_unavailable");}}boolean audio=s.capture()==Capture.AUDIO&&c.microphone()&&c.userVisible();if(s.capture()==Capture.AUDIO&&!c.microphone())d.add("microphone_permission_missing");else if(s.capture()==Capture.AUDIO&&!c.userVisible())d.add("audio_requires_visible_user_action");return new Plan(delivery,timing,audio,d);}
    public static ResponseEvent choiceEvent(InteractionSpec s,String eventId,String choiceId,long nowMs){validateId(eventId,"eventId");boolean ok=false;for(Choice x:s.choices())if(x.id().equals(choiceId)){ok=true;break;}if(!ok)throw new IllegalArgumentException("unknown choice");return new ResponseEvent(VERSION,eventId,s.interactionId(),nowMs,choiceId,null);}
    public static ResponseEvent audioEvent(InteractionSpec s,String eventId,String audioRef,long nowMs){validateId(eventId,"eventId");if(s.capture()!=Capture.AUDIO)throw new IllegalArgumentException("not audio interaction");if(blank(audioRef))throw new IllegalArgumentException("missing audio ref");return new ResponseEvent(VERSION,eventId,s.interactionId(),nowMs,null,audioRef);}
    public static Receipt receipt(InteractionSpec s,ReceiptStatus status,long nowMs,String evidence,Plan plan){return new Receipt(VERSION,s.interactionId(),status,nowMs,evidence,plan.downgrades());}
    public static String stringifyInteraction(InteractionSpec s){Map<String,Object>m=new LinkedHashMap<String,Object>();m.put("protocol",s.protocol());m.put("interactionId",s.interactionId());m.put("issuedAtMs",s.issuedAtMs());m.put("triggerAtMs",s.triggerAtMs());m.put("expiresAtMs",s.expiresAtMs());m.put("title",s.title());m.put("readyPrompt",s.readyPrompt());m.put("readyGate",s.readyGate());m.put("prompt",s.prompt());m.put("attention",s.attention().name());m.put("capture",s.capture().name());List<Object>cs=new ArrayList<Object>();for(Choice c:s.choices()){Map<String,Object>x=new LinkedHashMap<String,Object>();x.put("id",c.id());x.put("label",c.label());cs.add(x);}m.put("choices",cs);m.put("countdownMs",s.countdownMs());m.put("requiresExactTiming",s.requiresExactTiming());m.put("requestFullScreen",s.requestFullScreen());return MiniJson.stringify(m);}
    public static String stringifyResponse(ResponseEvent e){Map<String,Object>m=new LinkedHashMap<String,Object>();m.put("protocol",e.protocol());m.put("eventId",e.eventId());m.put("interactionId",e.interactionId());m.put("atMs",e.atMs());if(e.choiceId()!=null)m.put("choiceId",e.choiceId());if(e.audioRef()!=null)m.put("audioRef",e.audioRef());return MiniJson.stringify(m);}
    public static String stringifyReceipt(Receipt r){Map<String,Object>m=new LinkedHashMap<String,Object>();m.put("protocol",r.protocol());m.put("interactionId",r.interactionId());m.put("status",r.status().name());m.put("atMs",r.atMs());m.put("evidence",r.evidence());m.put("downgrades",r.downgrades());return MiniJson.stringify(m);}
    private static void validateShape(InteractionSpec s){Objects.requireNonNull(s);if(!VERSION.equals(s.protocol()))throw new IllegalArgumentException("bad protocol");validateId(s.interactionId(),"interactionId");if(blank(s.prompt())||s.prompt().length()>8000)throw new IllegalArgumentException("bad prompt");if(s.readyPrompt()!=null&&s.readyPrompt().length()>2000)throw new IllegalArgumentException("ready prompt too long");if(s.countdownMs()<0||s.countdownMs()>120000)throw new IllegalArgumentException("bad countdown");if(s.capture()==Capture.CHOICE&&s.choices().isEmpty())throw new IllegalArgumentException("choice capture without choices");if(s.choices().size()>24)throw new IllegalArgumentException("too many choices");Set<String>ids=new HashSet<String>();for(Choice c:s.choices()){validateId(c.id(),"choiceId");if(blank(c.label())||c.label().length()>240||!ids.add(c.id()))throw new IllegalArgumentException("bad/duplicate choice");}}
    private static boolean blank(String v){return v==null||v.trim().isEmpty();}private static void validateId(String v,String name){if(v==null||!ID.matcher(v).matches())throw new IllegalArgumentException("bad "+name);}private static String reqString(Map<String,Object>m,String k){String v=str(m,k,null);if(blank(v))throw new IllegalArgumentException("missing "+k);return v;}private static String str(Map<String,Object>m,String k,String d){Object v=m.get(k);return v==null?d:(String)v;}private static long num(Map<String,Object>m,String k,long d){Object v=m.get(k);return v==null?d:((Number)v).longValue();}private static boolean bool(Map<String,Object>m,String k,boolean d){Object v=m.get(k);return v==null?d:((Boolean)v).booleanValue();}
}
